### ISSUE TITLE
Can't see the robots

### ISSUE THREAD

**Issue by MartinaRuocco** [robotology-playground/pybullet-robot-envs#20]
[I work on Ubuntu 16.04]
I tried following the tutorial, after running the lines
`import gym` 
`env = gym.make('pybullet_robot_envs:iCubReach-v0')`
what happens is that OpenGL starts, I can definitely see a table and a ball but no robot. 
Same thing happens also with Panda. 

In the terminal I see a warning error after the item "MotionThreadFunc thread started":
`b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,839]:`
`b3Printf: /home/user/pybullet-robot-envs/pybullet_robot_envs/robot_data/iCub/: cannot extract mesh from '/home/user/pybullet-robot-envs/pybullet_robot_envs/robot_data/iCub//meshes/simmechanics/sim_sea_2-5_root_link_prt-binary.stl'`

and so on, similar messages for every .stl file.
Also I get this kinda of warning messages: 
`b3Printf: b3Warning[src/BulletInverseDynamics/MultiBodyTree.cpp,268]:`
`b3Printf: axis of motion not a unit axis ([0.965926 0.000000 0.258819]), will use normalized vector`

Any clue on how to solve this? 
I already tested pybullet and it works without any problem.

Many thanks in advance

**Comment by eleramp** [comment]
Hi @MartinaRuocco, your issue is likely related to a corrupted download of the robot meshes in [pybullet_robot_envs/robot_data](https://github.com/robotology-playground/pybullet-robot-envs/tree/master/pybullet_robot_envs/robot_data).

Did you install [Git LFS](https://git-lfs.github.com/) **before** cloning the repository? See point 2. in the [installation instructions](https://github.com/robotology-playground/pybullet-robot-envs#installation) of the Readme file. 
 
If not, please try to delete your local clone of the repository, install `Git LFS`, and then clone again the repository. 

If Git LFS is correctly installed on your machine, once you clone the repository the meshes are automatically downloaded from the git LFS remote server.

**Comment by MartinaRuocco** [comment]
Thank you @eleramp , now it works!
I think the problem is that I didn't install **Git LFS** correctly. 

I work on **Ubuntu 16.04** so I the correct procedure (for me) is to install it with
`curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash`
`sudo apt install git-lfs`
and set it up with
`git lfs install `
before proceeding with step 3

Very nice repo guys, I love your super clear instructions! Good job :))

ps: on another note, if I may suggest something, I think you should modify your step 1 instructions to specify the python version
`virtualenv ve_pybullet --python=python3`
